"""webauthn credentials and challenges

Revision ID: 53cb095d15bf
Revises: 08f1b55b470f
Create Date: 2026-05-02 21:14:13.763157

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '53cb095d15bf'
down_revision: str | None = '08f1b55b470f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# New AuditAction enum members added in this migration. Postgres needs an
# explicit ALTER TYPE because the original migration created a native PG
# ENUM. SQLite + MySQL store enum values as plain strings and accept new
# ones without DDL.
_NEW_AUDIT_ACTIONS = ("PASSKEY_REGISTER", "PASSKEY_LOGIN", "PASSKEY_DELETE")


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # `ADD VALUE IF NOT EXISTS` requires Postgres 9.6+. Each must run in
        # its own statement (PG can't add multiple values in one ALTER TYPE).
        for value in _NEW_AUDIT_ACTIONS:
            op.execute(f"ALTER TYPE auditaction ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_challenges_expires_at'), 'webauthn_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_webauthn_challenges_user_id'), 'webauthn_challenges', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_challenges_user_id'), table_name='webauthn_challenges')
    op.drop_index(op.f('ix_webauthn_challenges_expires_at'), table_name='webauthn_challenges')
    op.drop_table('webauthn_challenges')
    # ### end Alembic commands ###
