"""push_subscriptions

Revision ID: bfe5b3bac088
Revises: 53cb095d15bf
Create Date: 2026-05-06 00:51:09.139204

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bfe5b3bac088"
down_revision: str | None = "53cb095d15bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# New AuditAction enum members added in this migration. Postgres needs an
# explicit ALTER TYPE because the original migration created a native PG
# ENUM. SQLite + MySQL store enum values as plain strings and accept new
# ones without DDL.
_NEW_AUDIT_ACTIONS = ("PUSH_SUBSCRIBE", "PUSH_UNSUBSCRIBE", "PUSH_SEND_FAILED")


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # `ADD VALUE IF NOT EXISTS` requires Postgres 9.6+. Each must run in
        # its own statement (PG can't add multiple values in one ALTER TYPE).
        for value in _NEW_AUDIT_ACTIONS:
            op.execute(f"ALTER TYPE auditaction ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh_key", sa.LargeBinary(), nullable=False),
        sa.Column("auth_secret", sa.LargeBinary(), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("friendly_name", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_index(
        op.f("ix_push_subscriptions_user_id"),
        "push_subscriptions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
